### ISSUE TITLE
Gmail API send message example not working 

### ISSUE THREAD

**Issue by lecovi** [googleworkspace/python-samples#317]
# Summary

[Sending Message Example](https://developers.google.com/gmail/api/guides/sending#sending_messages) it seems to be outdated.

## Expected Behavior

Executing https://github.com/googleworkspace/python-samples/blob/master/gmail/snippet/send%20mail/send_message.py with proper credentials and a valid email address should send an email.

## Actual Behavior

```python
---------------------------------------------------------------------------
HttpError                                 Traceback (most recent call last)
Input In [203], in <cell line: 2>()
      1 # pylint: disable=E1101
      2 send_message = gmail_service.users().messages().send(
      3     userId="me",
      4     body=create_message
----> 5 ).execute()

File ~/src/ifts18/gworkspace-ifts18-helper/venv/lib/python3.10/site-packages/googleapiclient/_helpers.py:130, in positional.<locals>.positional_decorator.<locals>.positional_wrapper(*args, **kwargs)
    128     elif positional_parameters_enforcement == POSITIONAL_WARNING:
    129         logger.warning(message)
--> 130 return wrapped(*args, **kwargs)

File ~/src/ifts18/gworkspace-ifts18-helper/venv/lib/python3.10/site-packages/googleapiclient/http.py:938, in HttpRequest.execute(self, http, num_retries)
    936     callback(resp)
    937 if resp.status >= 300:
--> 938     raise HttpError(resp, content, uri=self.uri)
    939 return self.postproc(resp, content)

HttpError: <HttpError 400 when requesting https://gmail.googleapis.com/gmail/v1/users/me/messages/send?alt=json returned "'raw' RFC822 payload message string or uploading message via /upload/* URL required". Details: "[{'message': "'raw' RFC822 payload message string or uploading message via /upload/* URL required", 'domain': 'global', 'reason': 'invalidArgument'}]">
```

## Steps to Reproduce the Problem

1. Go to https://developers.google.com/gmail/api/guides/sending#sending_messages
2. Copy code and paste it in your local computer
1. Execute with proper credentials
1. See the outcome

## Specifications

- Python version (`python --version`): 3.10.4
- OS (Mac/Linux/Windows): Mac

**Comment by lecovi** [comment]
The problem is in the `create_message` structure, in the docs: 

```python
create_message = {
            'message': {

                'raw': encoded_message
            }
        }
```

When it should be:

```python
create_message = {
    'raw': encoded_message
}
```

**Comment by lecovi** [comment]
If you check in https://developers.google.com/gmail/api/reference/rest/v1/users.messages/send you can see that the [Message](https://developers.google.com/gmail/api/reference/rest/v1/users.messages#Message) has no `message` key.

```json
{
  "id": string,
  "threadId": string,
  "labelIds": [
    string
  ],
  "snippet": string,
  "historyId": string,
  "internalDate": string,
  "payload": {
    object ([MessagePart](https://developers.google.com/gmail/api/reference/rest/v1/users.messages#Message.MessagePart))
  },
  "sizeEstimate": integer,
  "raw": string
}
```

**Comment by andrewpaullin** [comment]
This change somehow broke:
https://github.com/googleworkspace/python-samples/blob/master/gmail/snippet/send%20mail/create_draft.py
which is also posted here:
https://developers.google.com/gmail/api/guides/drafts#python
Changing this back (adding "'message':" back) fixed this problem for me.
I still need to test this send_message.py file, will this soon.
Also, on this page:
https://github.com/googleworkspace/python-samples/issues/318
you said:
"
Expected Behavior
Executing https://github.com/googleworkspace/python-samples/blob/master/gmail/snippet/send%20mail/create_draft.py with proper credentials and a valid email address should send an email.
"
but I think you meant to say:
"...create_draft.py with proper credentials and a valid email address should CREATE A DRAFT email."
This is the proper behavior that resulted for me after the above mentioned change.
I really appreciate providing this for us, thank you for your efforts.
Please let me know anything more I can do to help.
I am still coming to speed on all this, etiquette in github etc, so please let me know anything with which I can improve. 
Thank you again and best regards,
Andrew Paullin
414-212-5372
andrew.paullin@gmail.com
